version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  api:
    command: bash -c "
        python manage.py migrate
        && python manage.py collectstatic --noinput
        && gunicorn split.wsgi:application --bind 0.0.0.0:80 --workers 3"
    environment:
      STAGE: "1"
    depends_on:
      - db
    ports:
      - "80:80"
  
  web:
    build: ./web/website
    command: yarn start
    depends_on:
      - api
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
