version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  api:
    command: bash -c "
        python manage.py migrate
        && python manage.py collectstatic --noinput
        && gunicorn split.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      STAGE: "1"
    depends_on:
      - db
    ports:
      - "8000:8000"
  
  web:
    build: ./web/website
    command: sh -c "
      yarn install --network-timeout 1000000
      && yarn start"
    depends_on:
      - api
    ports:
      - "3000:3000"
    volumes:
      - './web/website:/web'
      - '/web/node_modules'
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_HTTP_TIMEOUT=200
