version: '3'

services:
  api:
    command: bash -c "
        python manage.py migrate
        && python manage.py collectstatic --noinput
        && gunicorn split.wsgi:application --bind 0.0.0.0:443 --workers 3"
    environment:
      STAGE: "2"
    ports:
      - "443:443"
    env_file:
      - split.env