# Generated by Django 2.2.2 on 2019-06-05 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
