# Generated by Django 2.2.2 on 2019-06-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eip', '0002_auto_20190605_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogdocument',
            name='type',
            field=models.CharField(choices=[('KO', 'Kick off'), ('FU', 'Follow up'), ('D', 'Delivery')], max_length=2),
        ),
    ]
