# Generated by Django 2.2.1 on 2019-06-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_friend_group_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='payment_user',
            old_name='payment_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='friend',
            name='payment_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Friend'),
        ),
        migrations.AddField(
            model_name='group',
            name='friend_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Friend'),
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Friend'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Payment_user'),
        ),
    ]
