# Generated by Django 2.2.1 on 2019-06-08 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190607_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='friend_group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Payment_user',
        ),
    ]
