# Generated by Django 2.2.2 on 2019-06-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190616_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('mastercard', models.CharField(max_length=40)),
                ('expirancy', models.CharField(default='None', max_length=10)),
                ('cvc', models.CharField(default='None', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=42),
        ),
        migrations.DeleteModel(
            name='Payment_user',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.ManyToManyField(to='api.PaymentMethod'),
        ),
    ]
