# Generated by Django 2.2.2 on 2019-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190624_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='log',
            name='headers',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
