# Generated by Django 2.2.2 on 2019-06-24 15:22

import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190624_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='cookies',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
