# Generated by Django 2.2.2 on 2019-06-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_log_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='headers',
        ),
    ]
