# Generated by Django 2.2.2 on 2019-06-24 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_log_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='get',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='post',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
