# Generated by Django 2.2.2 on 2019-06-24 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190624_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
