# Generated by Django 2.2.2 on 2019-06-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_log_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='cookies',
        ),
    ]
