# Generated by Django 2.2.2 on 2019-06-26 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_log_cookies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expirancy',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='mastercard',
        ),
    ]
