# This is a basic workflow to help you get started with Actions

name: name

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the pre-prod branch
  push:
    branches: [ pre-prod ]
  pull_request:
    branches: [ pre-prod ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PREPROD_HOST }}
          USERNAME: ${{ secrets.PREPROD_USER }}
          PORT: ${{ secrets.PREPROD_PORT }}
          KEY: ${{ secrets.PREPROD_KEY }}
          script: |
            cd Split
            git pull
            git submodule foreach git pull origin master
            docker-compose -f docker-compose.yml -f docker-compose.preproduction.yml up --force-recreate -d web
